### PR TITLE
Ring Race Update

### PR DESCRIPTION
**Pull request by Prodigy4532**

### CODE REVIEW

**Comment by CoWinkKeyDinkInc** [comment]
You made a commit that adds a bunch of maps into this pull request, some of which I can't accept.  As said in the readme, please only involve one map per pull request and wait until I deal with it before adding commits that involve other maps.  I will take a look at your Ring Race fix though, but please add details to your changes next time.

**Comment by CoWinkKeyDinkInc** [comment]
So I noticed that you fixed the issue with the wool room regions, and made it TE with the team sizes and the wool locations, but what else did you fix?

**Comment by ghost** [comment]
@CoWinkKeyDinkInc I did it, no @Prodigy4532

**Comment by Prodigy4532** [comment]
@TiTo-418 ??

**Comment by CoWinkKeyDinkInc** [comment]
@TiTo-418 If you did this, why didn't you submit a pull request?  What did you change in the region files?

**Comment by ghost** [comment]
> you fixed the issue with the wool room regions, and made it TE with the team sizes and the wool locations, but what else did you fix?

**Comment by Prodigy4532** [comment]
Close this PR and i make only 1 for RR

**Pull request closed without merging**
