### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by Lmmb74**
Notable changes:
*Working Q-Boid (test xml included)
*Working Table Block (must work on portals [put them in own xml])
*Removed Dry DTC
*Removed A team gear map
*They were removed because I checked them, and they were not actually usable maps, so making xml files for them would be useless

### CODE REVIEW

**Comment by Lmmb74** [comment]
The commit 9b796aa called "Fixed Fairy Tales..." fixed the name of the folder, which was called Fary Tales... instead of Fairy Tales...

**Comment by CoWinkKeyDinkInc** [comment]
You can't recapture the hill once the opposing team gets it.  Also, I think I forgot to remove the bats in the map, they eventually despawn.

**Comment by CoWinkKeyDinkInc** [comment]
Oh yeah, could you also stick with the four space formatting?  It's more preferred to use this spacing in PGM XML.

**Comment by CoWinkKeyDinkInc** [comment]
## Table Block

Players are allowed to walk on top of their own entrances they're trying to defend, when they try to get in they should teleport onto [This](https://cloud.githubusercontent.com/assets/7586568/19458204/e5c47a36-9487-11e6-9e69-aab925b0dc9b.png) platform.

## Deadwater Docks and Pirates Grotto

The regions of the poisonous water seem to be messed up.  Rename Deadwater folder to Deadwater Docks

## Fairy Tales 2 Mini

I'm going to add a spawn island since this I have no idea where the spawn is even supposed to be.

## Bayou Battle

The map crashes, or it seems to fail to load.  I'll take a look at in in McEdit, you don't have to do anything.

**Comment by Lmmb74** [comment]
I will make a commit changing the format to the old 4-space formatting. Table Block, welp, I said I must work on the portals, since I actually did not know where they had to be. Deadwater Docks, I will change the name of the folder now. Fairy Tales 2 Mini, true story xD. If you want, I can make one :). Bayou Battle, I will check it right now too.

**Comment by CoWinkKeyDinkInc** [comment]
Anything else you want to do? I'll merge this despite the current problems if you say so.  I created two branches for the two unfinished maps if anyone wants to fix it.

**Comment by Lmmb74** [comment]
If you want, you can merge it. But Bayou Battle, you changed again the format xD. I will change it again now. After that, merge this.

**Comment by Lmmb74** [comment]
And do not make another branch for the unfinished maps. I will make a folder called WIP which will contain different gamemodes folders with the WIP maps of that gamemodes :D.

**Comment by Lmmb74** [comment]
Wtf, when I pulled your commits, the format was not changed as Github says :V.

**Comment by Lmmb74** [comment]
Seems like I did not pull before xD. So I fixed again the Bayou Battle format to 4-space style. And created WIP folder.
Soooooo..... you can merge it :)

**Comment by CoWinkKeyDinkInc** [comment]
Alright, thanks!!

**Pull request merged**
