### PR TITLE
Fixes (and there will be even more ;))

### PR DESCRIPTION
**Pull request by Lmmb74**
Fixed many typos, color codes, updated spawns in many maps, made some maps functional, fixed bugs in many of them, and reorganized some of the xml files

### CODE REVIEW

**Comment by CoWinkKeyDinkInc** [comment]
This all looks pretty good from what I can tell, but you should have made separate specific changes in each commit, or a separate commit for each map. You've done everything in two commits so it would be hard for me to reverse some of them if it's necessary, or follow with how the maps are updated. 

Please make a new PR that has a commit for each map.

**Comment by Lmmb74** [comment]
U.u, welp, ok :)

**Comment by CoWinkKeyDinkInc** [comment]
All of this looks great, just introduce the commits into smaller pieces, and make sure you test them to make sure it works too.

**Comment by Lmmb74** [comment]
I'm actually doing that, check my repo, the branch fixing

**Pull request closed without merging**
