### PR TITLE
Table Block - The WORK WORK WORK update :D

### PR DESCRIPTION
**Pull request by Lmmb74**
Welp, as said in the title, fully working table block update time has come :).

### CODE REVIEW

**Comment by CoWinkKeyDinkInc** [comment]
You should probably force the player's yaw to be in a fixed position after teleporting, also, like I said before, the team is allowed to walk on top of their own monument, they should only teleport like one block beneath obsidian.  A custom message should be put if you want to disable "safety wolls".  The blue team also cannot destroy the yellow team's entrances.

**Comment by CoWinkKeyDinkInc** [comment]
You didn't select the whole monument, as shown by the monument modes.

fart

**Comment by Lmmb74** [comment]
oops, gonna do it now :)

**Comment by Lmmb74** [comment]
Ready :)

**Comment by CoWinkKeyDinkInc** [comment]
I'll take a look at this tomorrow

**Comment by CoWinkKeyDinkInc** [comment]
I'll just assume this works

**Comment by Lmmb74** [comment]
:DDDD

**Pull request merged**
