### PR TITLE
Final Table Block fixes

### PR DESCRIPTION
**Pull request by Lmmb74**
Fully fixed regions, messages, typos and filters. Also updated version. Finally, the Table Block issue can be closed ;)

### CODE REVIEW

**Comment by CoWinkKeyDinkInc** [comment]
Renewables don't work in CardinalPGM just yet, please comment them out.

**Comment by Lmmb74** [comment]
But they are here u.u: http://ci.twizmwaz.in/job/Cardinal-unstable/

**Comment by CoWinkKeyDinkInc** [comment]
It's an unstable testing branch.

**Comment by Lmmb74** [comment]
It's actually reaaaaally stable

**Comment by CoWinkKeyDinkInc** [comment]
Well, okay then. The XML would still work fine anyway.

**Comment by Lmmb74** [comment]
Done it u.u

**Comment by CoWinkKeyDinkInc** [comment]
Cobblestone isn't being applied to item remove for some reason.

**Comment by Lmmb74** [comment]
Sure? I got no problem with that when I tested it

**Comment by CoWinkKeyDinkInc** [comment]
Oh well, great job 👍

**Comment by Lmmb74** [comment]
Yay :D

**Pull request merged**
